[package]
name = "rauth"
version = "1.0.0"
authors = ["Hèctor Morales <hector.morales.carnice@gmail.com>"]
edition = "2021"

[dependencies]
diesel = { version = "1.4.8", features = ["postgres", "chrono", "r2d2"] } # postgres orm
tonic = "0.6.2" # gRPC
prost = "0.9.0" # protobuf
tokio = { version = "1.15.0", features = ["full"] }
lettre = "0.9.6"
regex = "1.5.4"
dotenv = "0.15.0"
base64 = "0.13.0"
sha256 = "1.0.2"
openssl = "0.10.35"
lazy_static = "1.4.0"
jsonwebtoken = "7.2.0"
log = "0.4.14"
tera = "1.15.0" # templates processor

[build-dependencies]
tonic-build = "0.6.2"

[lib]
name = "rauth"
path = "src/lib.rs"

[features]
integration-tests = []