[package]
name = "rauth"
version = "1.0.0"
authors = ["Hèctor Morales <hector.morales.carnice@gmail.com>"]
edition = "2021"

[dependencies]
async_once = "0.2.6"
async-trait = "0.1.57"
sqlx = { version = "0.6.1", features = [
    "runtime-tokio-rustls",
    "postgres",
    "chrono",
] }
redis = { version = "0.22.1", features = ["tokio-comp"] }
reool = "0.30.0"
tonic = "0.8.1" # gRPC
prost = "0.11.0" # protobuf
tokio = { version = "1.21.0", features = ["macros"] }
regex = "1.6.0"
dotenv = "0.15.0"
env_logger = "0.10.0"
base64 = "0.13.0"
sha256 = "1.0.3"
openssl = "0.10.41"
libreauth = "0.15.0"
rand = "0.8.5"
lazy_static = "1.4.0"
jsonwebtoken = "8.1.1"
log = "0.4.17"
chrono = "0.4.22"
serde = "1.0.144" # data parser
serde_json = "1.0.85"
lettre = "0.10.1"
tera = "1.17.0" # template engine
lapin = "2.1.1"
protoc = "2.27.1"

[build-dependencies]
tonic-build = "0.8.0"

[lib]
name = "rauth"
path = "src/lib.rs"

[[bin]]
name = "rauth"
path = "src/main.rs"
