[package]
name = "tp-auth"
version = "0.1.0"
authors = ["Hèctor Morales <hector.morales.carnice@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
