[package]
name = "tp-auth"
version = "0.1.0"
authors = ["Hèctor Morales <hector.morales.carnice@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# database drivers
diesel = { version = "1.4.5", features = ["postgres"] }
diesel-derive-enum = { version = "1", features = ["postgres"] }
# gRPC server/client
tonic = "0.3.0"
prost = "0.6"
# Async runtime
tokio = { version = "0.2", features = ["full"] }
regex = "1"
# environment configurations
dotenv = "0.15.0"
dotenv_codegen = "0.15.0"
rand = "0.7.3"
typemap = "0.3.3"
# static structures
phf = { version = "0.7.24", features = ["macros"] }
chrono = "0.4.19"
#serde = "1.0.118"

[build-dependencies]
tonic-build = "0.3.0"