[package]
name = "rauth"
version = "1.0.0"
authors = ["Hèctor Morales <hector.morales.carnice@gmail.com>"]
edition = "2021"

[dependencies]
async_once = "0.2.6"
async-trait = "0.1.57"
base64 = "0.21.0"
chrono = "0.4.22"
dotenv = "0.15.0"
env_logger = "0.10.0"
jsonwebtoken = "8.1.1"
lapin = "2.1.1"
lazy_static = "1.4.0"
lettre = "0.10.1"
libreauth = "0.15.0"
log = "0.4.17"
openssl = "0.10.41"
prost = { version = "0.11.0", optional = true } # protobuf
protoc = { version = "2.27.1", optional = true }
rand = "0.8.5"
redis = { version = "0.23.0", features = ["tokio-comp"] }
regex = "1.6.0"
reool = "0.30.0"
serde = "1.0.144" # data parser
serde_json = "1.0.85"
sha256 = "1.0.3"
sqlx = { version = "0.6.1", features = [
    "runtime-tokio-rustls",
    "postgres",
    "chrono",
] }
strum = "0.24"
strum_macros = "0.24"
tera = "1.17.0" # template engine
tokio = { version = "1.24.1", features = ["macros"] }
tonic = { version = "0.9.1", optional = true } # gRPC
actix-web  = { version = "4.3.1", optional = true } # rest

[build-dependencies]
tonic-build = "0.9.1"

[lib]
name = "rauth"
path = "src/lib.rs"

[features]
default = ["grpc", "rest"]
grpc = ["prost", "protoc", "tonic"]
rest = ["actix-web"]

[[bin]]         
name = "grpc"    
path = "src/bin/grpc.rs"
default-features = false
required-features = ["grpc"]

[[bin]]         
name = "rest"    
path = "src/bin/rest.rs"
default-features = false
required-features = ["rest"]