[package]
name = "oauth"
version = "0.2.0"
authors = ["Hèctor Morales <hector.morales.carnice@gmail.com>"]
edition = "2018"

[dependencies]
diesel = { version = "1.4.5", features = ["postgres", "chrono", "r2d2"] }
tonic = "0.5.0"
prost = "0.8.0"
tokio = { version = "1.2.0", features = ["full"] }
lettre = "0.9.6"
lettre_email = "0.9"
regex = "1"
dotenv = "0.15.0"
rand = "0.8.3"
chrono = "0.4.19"
rand_core = { version = "0.6.1", features = ["getrandom"] }
base64 = "0.13.0"
openssl = "0.10.32"
lazy_static = "1.4.0"
serde = "1.0.123"
bson = "1.2.0"
libreauth = "0.14.1"

[dependencies.mongodb]
version = "1.2.0"
default-features = false
features = ["sync"]

[build-dependencies]
tonic-build = "0.5.0"