[package]
name = "oauth"
version = "0.2.0"
authors = ["Hèctor Morales <hector.morales.carnice@gmail.com>"]
edition = "2018"

[dependencies]
diesel = { version = "1.4.7", features = ["postgres", "chrono", "r2d2"] }
tonic = "0.5.0"
prost = "0.8.0"
tokio = { version = "1.8.2", features = ["full"] }
lettre = "0.9.6"
lettre_email = "0.9.4"
regex = "1.5.4"
dotenv = "0.15.0"
rand = "0.8.4"
chrono = "0.4.19"
rand_core = { version = "0.6.3", features = ["getrandom"] }
base64 = "0.13.0"
openssl = "0.10.35"
lazy_static = "1.4.0"
serde = "1.0.126"
bson = "1.2.2"
libreauth = "0.14.1"
jsonwebtoken = "7.2.0"
log = "0.4.14"
env_logger = "0.9.0"

[dependencies.mongodb]
version = "1.2.2"
default-features = false
features = ["sync"]

[build-dependencies]
tonic-build = "0.5.1"