[package]
name = "rauth"
version = "1.0.0"
authors = ["Hèctor Morales <hector.morales.carnice@gmail.com>"]
edition = "2021"

[dependencies]
diesel = { version = "1.4.8", features = ["postgres", "chrono", "r2d2"] } # postgres client
r2d2_redis = "0.14.0" # sync redis connection pool
tonic = "0.6.2" # gRPC
prost = "0.9.0" # protobuf
tokio = { version = "1.15.0", features = ["full"] }
regex = "1.5.4"
dotenv = "0.15.0"
env_logger = "0.9.0"
base64 = "0.13.0"
sha256 = "1.0.2"
openssl = "0.10.35"
libreauth = "0.14.1"
rand = "0.8.4"
lazy_static = "1.4.0"
jsonwebtoken = "8.0.1"
log = "0.4.14"
chrono = "0.4.19"
serde = "1.0.133" # data parser
# lettre = "0.9.6" # mailer builder + transports
# lettre_email = "0.9.4"
lettre = "0.10.0-rc.4"
tera = "1.15.0" # template engine

[build-dependencies]
tonic-build = "0.6.2"

[lib]
name = "rauth"
path = "src/lib.rs"

[[bin]]
name = "rauth"
path = "src/main.rs"

[features]
integration-test = []