[package]
name = "oauth"
version = "0.1.0"
authors = ["Hèctor Morales <hector.morales.carnice@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# database drivers
diesel = { version = "1.4.5", features = ["postgres", "chrono", "r2d2"] }
# diesel-derive-enum = { version = "1", features = ["postgres"] }
# gRPC server/client
tonic = "0.4.0"
prost = "0.7.0"
# Async runtime
tokio = { version = "1.2.0", features = ["full"] }
regex = "1"
# environment configurations
dotenv = "0.15.0"
# dotenv_codegen = "0.15.0"
rand = "0.8.3"
# typemap = "0.3.3"
# static structures
# phf = { version = "0.7.24", features = ["macros"] }
# rust-crypto = "0.2.36"
chrono = "0.4.19"
#shamir = "~1.0"
enum_derive = "0.1.7"
custom_derive = "0.1.7"
# pwbox = "0.4.0"
rand_core = { version = "0.6.1", features = ["getrandom"] }
base64 = "0.13.0"
openssl = "0.10.32"
lazy_static = "1.4.0"
serde = "1.0.123"
bson = "1.2.0"

[dependencies.mongodb]
version = "1.2.0"
default-features = false
features = ["sync"]

[build-dependencies]
tonic-build = "0.4.0"