services:
    # postgres:
    #     container_name: rauth-postgres
    #     image: docker.io/postgres:alpine3.15
    #     restart: on-failure
    #     # ports:
    #     #     - 5432:5432
    #     volumes:
    #         - dbdata:/data/postgres
    #         - ./migrations/.postgres:/docker-entrypoint-initdb.d
    #     security_opt:
    #         label: disable
    #     env_file:
    #         - ".env"
            
    redis:
        container_name: rauth-redis
        image: docker.io/redis:alpine3.15
        restart: always
        # ports:
        #     - 6379:6379

    # rauth:
    #     container_name: rauth-server
    #     image: localhost/alvidir/rauth:1.0.0-server
    #     restart: always
    #     depends_on: 
    #         - postgres
    #         - redis
    #     env_file:
    #         - .env

    # envoy:
    #     container_name: rauth-envoy
    #     image: docker.io/envoyproxy/envoy-alpine:v1.21-latest
    #     restart: always
    #     ports:
    #         - 8080:8080
    #         - 9901:9901
    #     volumes:
    #         - ./envoy:/etc/envoy
    #     security_opt:
    #         label: disable
    #     depends_on: 
    #         - rauth
    #     command: /usr/local/bin/envoy --log-level debug -c /etc/envoy/envoy.yaml

    nginx:
        container_name: rauth-nginx
        image: localhost/alvidir/rauth:1.0.0-nginx
        restart: always
        ports:
            - 9080:80
            - 9443:443
        volumes:
            - ./nginx:/etc/nginx/conf.d
        security_opt:
            label: disable
        depends_on: 
            - redis
        env_file:
            - .env

volumes:
    dbdata:
    pgdata: