version: '3.8'

services:
    ### ENVOY PROXY ###
    envoy:
        container_name: tp-auth-envoy
        image: alvidir/tp-auth:0.1.0-envoy
        restart: always
        ports:
            - "5050:5050"
            - "9901:9901"
        networks:
            - ingress
    
    ### DATABASE ###
    postgres:
        container_name: postgres
        image: postgres:latest
        restart: on-failure
        volumes:
            - dbdata:/data/postgres
            - "./migrations/.default:/docker-entrypoint-initdb.d"
        networks: 
            - database
        env_file:
            - ".env"
        depends_on:
            - tp-auth-envoy
           
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:4.30
        restart: always
        depends_on:
            - postgres
        ports:
            - "${PGADMIN_PORT}:80"
        volumes:
            - pgdata:/root/.pgadmin
        networks: 
            - database
        env_file:
            - ".env"

    ### BACKEND ###
    tp-auth:
        container_name: tp-auth-server
        image: alvidir/tp-auth:0.1.0-server
        restart: always
        networks: 
            - ingress
            - database
        depends_on: 
            - postgres
            - envoy
        env_file:
            - .env

networks:
    # Ingress network works as bridge between envoyproxy and the available services
    ingress:
        name: ingress
        driver: bridge
 
    # Database network is the bridge between domain environment and the sql databases
    database:
        name: database
        driver: bridge

volumes:
    dbdata:
    pgdata: