services:
    postgres:
        container_name: postgres
        image: docker.io/postgres:alpine3.15
        restart: on-failure
        ports:
            - "5432:5432"
        volumes:
            - dbdata:/data/postgres
            - ./migrations/.postgres:/docker-entrypoint-initdb.d
        security_opt:
            label: disable
        env_file:
            - ".env"
            
    redis:
        container_name: redis
        image: docker.io/redis:alpine3.15
        restart: always
        ports:
            - "6379:6379"
    
    envoy:
        container_name: rauth-envoy
        image: localhost/alvidir/rauth:1.0.0-envoy
        restart: always
        ports:
            - "8080:8080"
            - "9901:9901"
        security_opt:
            label: disable

    rauth:
        container_name: rauth-server
        image: localhost/alvidir/rauth:1.0.0-server
        restart: always
        depends_on: 
            - postgres
            - redis
        env_file:
            - .env

volumes:
    dbdata:
    pgdata: