name: Continuous integration

on:
  - push
  - pull_request

jobs:
  run_unitary_tests:
    name: Run unitary tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install protoc
        uses: arduino/setup-protoc@v1
        with:
          version: "3.x"

      - name: Cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose

  release_version:
    name: Release version
    runs-on: ubuntu-latest

    needs:
      - run_unitary_tests

    if: ${{ github.ref == 'refs/heads/main' && !contains(join(needs.*.conclusion), 'failure') }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create tag
        id: tagging
        uses: anothrNick/github-tag-action@1.45.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tagging.outputs.new_tag }}
          token: ${{ secrets.PAT }}
