name: Run tests

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  run_unitary_tests:
    name: Run unitary tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: icepuma/rust-action@master

      - name: Cargo test
        run: cargo test --verbose
